{"version": "0.1", "tests": [{"id": "functional.test_toolbox.TestForTool_rawrsampler.test_tool_000000", "has_data": true, "data": {"tool_id": "rawrsampler", "tool_version": "0.1.0", "test_index": 0, "time_seconds": 12.222090482711792, "inputs": {"input1": {"src": "hda", "id": "2891970512fa2d5a"}, "input2": {"src": "hda", "id": "5729865256bc2525"}}, "status": "failure", "problem_type": "builtins.AssertionError", "problem_log": "  File \"/home/kiki/anaconda3/envs/_galaxy_/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/home/kiki/anaconda3/envs/_galaxy_/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n  File \"/home/kiki/Work/galaxy/test/functional/test_toolbox.py\", line 115, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/home/kiki/Work/galaxy/test/functional/test_toolbox.py\", line 49, in do_it\n    register_job_data=register_job_data,\n  File \"/home/kiki/Work/galaxy/lib/galaxy/tool_util/verify/interactor.py\", line 1248, in verify_tool\n    assert data_list or data_collection_list\n\n-------------------- >> begin captured logging << --------------------\nmultipart.multipart: DEBUG: Calling on_field_start with no data\nmultipart.multipart: DEBUG: Calling on_field_name with data[0:4]\nmultipart.multipart: DEBUG: Calling on_field_data with data[5:48]\nmultipart.multipart: DEBUG: Calling on_field_end with no data\nmultipart.multipart: DEBUG: Calling on_end with no data\n--------------------- >> end captured logging << ---------------------"}}], "summary": {"num_tests": 1, "num_failures": 1, "num_errors": 0, "num_skips": 0}, "exit_code": 1}